baseUrl = "https://gowebexamples.urairat.com/"
languageCode = "th-th"
title = "Go เว็บตัวอย่าง"
PygmentsCodeFences = true
PygmentsStyle = "trac"
enableRobotsTXT = true

[Params]
description = "Go เว็บตัวอย่าง สามารถที่จะทำความเข้าใจได้ง่ายโดยการศึกษาจากโค้ดตัวอย่างที่มีให้ หากพร้อมแล้วพวกเราก็มาเริ่มเรียนรู้การสร้างเว็บไซต์ด้วยภาษา Go กันดีกว่า"
